version: '3.9'
services:
  postgresql:
    image: postgres
    container_name: pantarei-postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=pantarei
      - POSTGRES_PASSWORD=pantarei
      - POSTGRES_DATABASE=pantarei
    command: postgres
    restart: always
  redis:
    image: redis:alpine3.14
    container_name: pantarei-redis
    ports:
      - "6379:6379"
